### ISSUE TITLE
出来苹果图标加载一半就卡那了也没提示

### ISSUE THREAD

**Issue by smile2014** [hibobmaster/HP-15-dc1010nr-hackintosh#1]

**Comment by hibobmaster** [comment]
请提供一下使用的EFI，此外开启verbose模式，看卡在哪里

**Comment by smile2014** [comment]
EFI-for-Monterey-v0.7.7/EFI  我处理器和你一样，显卡是1660T  请问verbose 设置成几呢

**Comment by hibobmaster** [comment]
[EFI-for-Monterey-v0.7.zip](https://github.com/hibobmaster/HP-15-dc1010nr-hackintosh/files/7760526/EFI-for-Monterey-v0.7.zip)
试试这个EFI

**Comment by smile2014** [comment]
谢谢，我看看

**Comment by smile2014** [comment]
刚给的EFI 是支持mac big sur 的吧11版本。

**Comment by smile2014** [comment]
启动提示文件目录不存在。读码的时候。

**Comment by hibobmaster** [comment]
不支持，是专门用于macOS 12的
Big Sur请用**EFI-for-Big-Sur.zip**:  https://github.com/hibobmaster/HP-15-dc1010nr-hackintosh/releases/tag/0.7.4

**Comment by smile2014** [comment]
能发个12的镜像连接我不，你给的下面这个我试过不行。。

**Comment by hibobmaster** [comment]
http://swcdn.apple.com/content/downloads/06/34/002-42435-A_MA7OBDUK86/6xzypeod1xebasc92qkw2iv44e1j9pv09f/InstallAssistant.pkg

**Comment by hibobmaster** [comment]
我想起来了，你这个型号可能核显是被屏蔽的，请测试核显是否可以运行，如果不行，就整不了黑果，因为在新macOS下没有Nvidia的驱动了。

**Comment by smile2014** [comment]
你给的镜像pkg windows上没办法识别做镜像吧

**Comment by hibobmaster** [comment]
是的，windows要参考这里的教程
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos

**Comment by smile2014** [comment]
谢谢了，我看看。
